export const ENEMY_CATALOG = [
  {
    id: "worm_basic",
    name: "Worm Pack",
    short: "Long zigzagging worms from the northwest branch.",
    description: "Fast or medium worm swarms that descend while weaving left and right. They define the worm branch identity before elite and boss encounters.",
    family: "worm",
    role: "normal",
    stats: [
      "Movement: zigzag downward",
      "Branch: northwest",
      "Profile: light to medium HP",
    ],
  },
  {
    id: "beetle_basic",
    name: "Beetle Pack",
    short: "Slow armored beetles from the northeast branch.",
    description: "Heavy beetles advance slowly but soak much more damage than spiders or worms. This branch is the durable attrition path.",
    family: "beetle",
    role: "normal",
    stats: [
      "Movement: slow downward march",
      "Branch: northeast",
      "Profile: larger bodies, high HP, low speed",
    ],
  },
  {
    id: "spider_basic",
    name: "Spider Pack",
    short: "Default fast attack spiders from the south branch.",
    description: "Spider enemies are the baseline swarm branch: quicker, lighter, and easier to read as the standard combat faction.",
    family: "spider",
    role: "normal",
    stats: [
      "Movement: direct downward advance",
      "Branch: south",
      "Profile: baseline HP and speed",
    ],
  },
  {
    id: "worm_elite",
    name: "Elite Worm",
    short: "Large worm elite for the northwest branch.",
    description: "A much larger worm that keeps the branch motion style but becomes a miniboss-grade endurance target.",
    family: "worm",
    role: "elite",
    stats: [
      "Large elite target",
      "Retains worm branch motion",
      "High HP, lethal on breach",
    ],
  },
  {
    id: "beetle_elite",
    name: "Elite Beetle",
    short: "Large armored beetle elite for the northeast branch.",
    description: "A large beetle miniboss with extremely high health and very slow movement, built to pressure sustained damage setups.",
    family: "beetle",
    role: "elite",
    stats: [
      "Very high HP",
      "Larger elite body",
      "Very slow",
      "Lethal on breach",
    ],
  },
  {
    id: "spider_elite",
    name: "Elite Spider",
    short: "Large spider elite for the south branch.",
    description: "A giant spider miniboss that represents the default elite threat and gates legendary rewards before bosses.",
    family: "spider",
    role: "elite",
    stats: [
      "Large elite target",
      "Moderate elite speed",
      "Lethal on breach",
    ],
  },
  {
    id: "worm_boss",
    name: "Worm Boss",
    short: "Final worm-branch boss.",
    description: "The worm branch ends with a large butterfly-form boss. When that first form is fully killed, it splits into two elite worms and the fight continues against both.",
    family: "worm",
    role: "boss",
    stats: [
      "Branch end boss",
      "Butterfly first phase",
      "Large butterfly first phase",
      "Splits into 2 elite worms on death",
      "Pushback resistance: 0.25",
      "Shield knockback distance: 0.25 size",
    ],
  },
  {
    id: "beetle_boss",
    name: "Beetle Boss",
    short: "Final beetle-branch boss.",
    description: "The beetle branch ends with a huge armored beetle boss that periodically spawns tiny fast beetles with 1 HP.",
    family: "beetle",
    role: "boss",
    stats: [
      "Branch end boss",
      "Summons a 1 HP fast beetle every 1s",
      "Much larger boss body",
      "No personal shield",
      "Pushback resistance: 0.25",
      "Shield knockback distance: 0.25 size",
    ],
  },
  {
    id: "spider_boss",
    name: "Spider Boss",
    short: "Shielded final spider boss.",
    description: "The spider branch ends with the shielded giant spider boss. It is currently the only boss planned to retain a personal shield long-term.",
    family: "spider",
    role: "boss",
    stats: [
      "Branch end boss",
      "Personal shield equals HP",
      "Only boss with personal shield",
      "Pushback resistance: 0.25",
      "Shield knockback distance: 0.25 size",
    ],
  },
];
